const Constant = {
    ADD_TODO: "ADD_TODO",
    LOADING: "LOADING",
    ADD_PUBLIC_DETAIL: "ADD_PUBLIC_DETAIL",
    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER",
    REQUEST_DATA: "REQUEST_DATA",
    RECEIVE_DATA: "RECEIVE_DATA",
    DATA_ERROR: "DATA_ERROR",
    FETCH_REQUEST: "FETCH_REQUEST",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
    // product Detail
    FETCH_PRODUCT: "FETCH_PRODUCT",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR",
    // city
    POPULAR_DESTINATIONS_FETCH: "POPULAR_DESTINATIONS_FETCH",
    POPULAR_DESTINATIONS_SUCCESS: "POPULAR_DESTINATIONS_SUCCESS",
    POPULAR_DESTINATIONS_ERROR: "POPULAR_DESTINATIONS_ERROR",
    // banners
    BANNERS_SUCCESS: "BANNERS_SUCCESS",
    BANNERS_ERROR: "BANNERS_ERROR",
    // tours
    FILTER_RESET: "FILTER_RESET",
    FETCH_TOURS: "FETCH_TOURS",
    FETCH_TOURS_SUCCESS: "FETCH_TOURS_SUCCESS",
    FETCH_TOURS_ERROR: "FETCH_TOURS_ERROR",
    CHANGED_FILTER_VISIBILITY: "CHANGED_FILTER_VISIBILITY",

    // search
    CHANGED_SEARCH_VISIBILITY: "CHANGED_SEARCH_VISIBILITY",
    UPDATED_SEARCH_TEXT_VALUE: "UPDATED_SEARCH_TEXT_VALUE",
    SUGGESTIONS_GET: "SUGGESTIONS_GET",
    SUGGESTIONS_GET_SUCCESS: "SUGGESTIONS_GET_SUCCESS",
    SUGGESTIONS_GET_ERROR: "SUGGESTIONS_GET_ERROR",
    SUGGESTIONS_SEARCH_VALUE_SET: "SUGGESTIONS_SEARCH_VALUE_SET",
    SUGGESTIONS_SEARCH_VALUE_CLEAR: "SUGGESTIONS_SEARCH_VALUE_CLEAR",
    LOAD_SUGGESTIONS_BEGIN: "LOAD_SUGGESTIONS_BEGIN",
    // Recent Search
    RECENT_SEARCH_SUCCESS: "RECENT_SEARCH_SUCCESS",
    RECENT_SEARCH_ERROR: "RECENT_SEARCH_ERROR",
    // Popular Search
    POPULAR_SEARCH: "POPULAR_SEARCH",
    POPULAR_SEARCH_ERROR: "POPULAR_SEARCH_ERROR",
    POPULAR_SEARCH_SUCCESS: "POPULAR_SEARCH_SUCCESS",
    SET_FILTER_HIDDEN: "SET_FILTER_HIDDEN"
}
export default Constant
