const Constant = {
    ADD_TODO: "ADD_TODO",
    LOADING: "LOADING",
    ADD_PUBLIC_DETAIL: "ADD_PUBLIC_DETAIL",
    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER",
    REQUEST_DATA: "REQUEST_DATA",
    RECEIVE_DATA: "RECEIVE_DATA",
    DATA_ERROR: "DATA_ERROR",
    FETCH_REQUEST: "FETCH_REQUEST",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
    // product Detail
    FETCH_PRODUCT: "FETCH_PRODUCT",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR",
    // city
    POPULAR_DESTINATIONS_FETCH: "POPULAR_DESTINATIONS_FETCH",
    POPULAR_DESTINATIONS_SUCCESS: "POPULAR_DESTINATIONS_SUCCESS",
    POPULAR_DESTINATIONS_ERROR: "POPULAR_DESTINATIONS_ERROR",
    // tours
    FETCH_TOURS: "FETCH_TOURS",
    FETCH_TOURS_SUCCESS: "FETCH_TOURS_SUCCESS",
    FETCH_TOURS_ERROR: "FETCH_TOURS_ERROR",
    // list
    SET_FILTER_HIDDEN: "SET_FILTER_HIDDEN"
}

export default Constant
